### ISSUE TITLE
ImmutableTree.getRangeProof could use len(bytes) != 0 instead of bytes != nil for bullet proofing of condition slips

### ISSUE THREAD

**Issue by odeke-em** [cosmos/iavl#341] opened 2020-12-13 09:23 UTC
I’ve just noticed this code https://github.com/cosmos/iavl/blob/f5c104d6591ea3ec0c4933f5a00c530632d471a5/proof_range.go#L376
whose condition won’t pass if KeyStart or KeyEnd are empty slices and not just from the zero value as per 
https://play.golang.org/p/dekgCHI4lOv

I’d think that ideally if I passed in a populated keyStart and a zero value keyEnd, that the first condition should trigger and return an error ASAP.

And ditto for these comparisons https://github.com/cosmos/iavl/blob/f5c104d6591ea3ec0c4933f5a00c530632d471a5/proof_range.go#L394-L395

**Comment by odeke-em** [comment] 2020-12-13 09:23
Kindly cc-ing @erikgrinaker @marbar3778.

**Comment by erikgrinaker** [comment] 2020-12-13 09:54
I'm not sure if I agree. I haven't looked to closely at this code in particular, but in the context of KV databases, `nil` usually means "no key" and is used as a marker for e.g. minus infinity (start) or infinity (end). `[]byte{}` on the other hand is a valid key, specifically the empty key. So start=nil and end=[]byte{} is the range from minus infinity to []byte{} (exclusive), which will always be an empty range, but is still a valid range.

**Comment by erikgrinaker** [comment] 2020-12-14 09:22
Closing this, as I believe this is working as intended.

**Closed by erikgrinaker** 2020-12-14 09:22 UTC

**Comment by odeke-em** [comment] 2020-12-14 09:25
Cool, thank you Erik!
